"""add financial contracts

Revision ID: 1d64cfe5b58b
Revises: 4d1a2b3c4e5f
Create Date: 2026-08-30 16:26:13.395198

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1d64cfe5b58b"
down_revision: str | Sequence[str] | None = "4d1a2b3c4e5f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "financial_contracts",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("minimum_confidence", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column(
            "minimum_supported_claim_ratio", sa.Numeric(precision=5, scale=4), nullable=False
        ),
        sa.Column("required_claim_types", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("financial_contracts")
    # ### end Alembic commands ###
