"""initial database schema

Revision ID: 5e3161c065ab
Revises: 
Create Date: 2026-08-27 22:47:32.449340

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '5e3161c065ab'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
